# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AssignOrderData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_purchase_order: int=None, id_receipt: int=None, user: str=None):  # noqa: E501
        """AssignOrderData - a model defined in Swagger

        :param id_purchase_order: The id_purchase_order of this AssignOrderData.  # noqa: E501
        :type id_purchase_order: int
        :param id_receipt: The id_receipt of this AssignOrderData.  # noqa: E501
        :type id_receipt: int
        :param user: The user of this AssignOrderData.  # noqa: E501
        :type user: str
        """
        self.swagger_types = {
            'id_purchase_order': int,
            'id_receipt': int,
            'user': str
        }

        self.attribute_map = {
            'id_purchase_order': 'id_purchase_order',
            'id_receipt': 'id_receipt',
            'user': 'user'
        }
        self._id_purchase_order = id_purchase_order
        self._id_receipt = id_receipt
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'AssignOrderData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AssignOrderData of this AssignOrderData.  # noqa: E501
        :rtype: AssignOrderData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_purchase_order(self) -> int:
        """Gets the id_purchase_order of this AssignOrderData.


        :return: The id_purchase_order of this AssignOrderData.
        :rtype: int
        """
        return self._id_purchase_order

    @id_purchase_order.setter
    def id_purchase_order(self, id_purchase_order: int):
        """Sets the id_purchase_order of this AssignOrderData.


        :param id_purchase_order: The id_purchase_order of this AssignOrderData.
        :type id_purchase_order: int
        """

        self._id_purchase_order = id_purchase_order

    @property
    def id_receipt(self) -> int:
        """Gets the id_receipt of this AssignOrderData.


        :return: The id_receipt of this AssignOrderData.
        :rtype: int
        """
        return self._id_receipt

    @id_receipt.setter
    def id_receipt(self, id_receipt: int):
        """Sets the id_receipt of this AssignOrderData.


        :param id_receipt: The id_receipt of this AssignOrderData.
        :type id_receipt: int
        """

        self._id_receipt = id_receipt

    @property
    def user(self) -> str:
        """Gets the user of this AssignOrderData.


        :return: The user of this AssignOrderData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this AssignOrderData.


        :param user: The user of this AssignOrderData.
        :type user: str
        """

        self._user = user
