# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BlacklistData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, dni: str=None, business_id: int=None, full_names: str=None, reason_restriction: str=None, image_path: str=None, observations: str=None, user: str=None):  # noqa: E501
        """BlacklistData - a model defined in Swagger

        :param dni: The dni of this BlacklistData.  # noqa: E501
        :type dni: str
        :param business_id: The business_id of this BlacklistData.  # noqa: E501
        :type business_id: int
        :param full_names: The full_names of this BlacklistData.  # noqa: E501
        :type full_names: str
        :param reason_restriction: The reason_restriction of this BlacklistData.  # noqa: E501
        :type reason_restriction: str
        :param image_path: The image_path of this BlacklistData.  # noqa: E501
        :type image_path: str
        :param observations: The observations of this BlacklistData.  # noqa: E501
        :type observations: str
        :param user: The user of this BlacklistData.  # noqa: E501
        :type user: str
        """
        self.swagger_types = {
            'dni': str,
            'business_id': int,
            'full_names': str,
            'reason_restriction': str,
            'image_path': str,
            'observations': str,
            'user': str
        }

        self.attribute_map = {
            'dni': 'dni',
            'business_id': 'business_id',
            'full_names': 'full_names',
            'reason_restriction': 'reason_restriction',
            'image_path': 'image_path',
            'observations': 'observations',
            'user': 'user'
        }
        self._dni = dni
        self._business_id = business_id
        self._full_names = full_names
        self._reason_restriction = reason_restriction
        self._image_path = image_path
        self._observations = observations
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'BlacklistData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BlacklistData of this BlacklistData.  # noqa: E501
        :rtype: BlacklistData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dni(self) -> str:
        """Gets the dni of this BlacklistData.


        :return: The dni of this BlacklistData.
        :rtype: str
        """
        return self._dni

    @dni.setter
    def dni(self, dni: str):
        """Sets the dni of this BlacklistData.


        :param dni: The dni of this BlacklistData.
        :type dni: str
        """

        self._dni = dni

    @property
    def business_id(self) -> int:
        """Gets the business_id of this BlacklistData.


        :return: The business_id of this BlacklistData.
        :rtype: int
        """
        return self._business_id

    @business_id.setter
    def business_id(self, business_id: int):
        """Sets the business_id of this BlacklistData.


        :param business_id: The business_id of this BlacklistData.
        :type business_id: int
        """

        self._business_id = business_id

    @property
    def full_names(self) -> str:
        """Gets the full_names of this BlacklistData.


        :return: The full_names of this BlacklistData.
        :rtype: str
        """
        return self._full_names

    @full_names.setter
    def full_names(self, full_names: str):
        """Sets the full_names of this BlacklistData.


        :param full_names: The full_names of this BlacklistData.
        :type full_names: str
        """

        self._full_names = full_names

    @property
    def reason_restriction(self) -> str:
        """Gets the reason_restriction of this BlacklistData.


        :return: The reason_restriction of this BlacklistData.
        :rtype: str
        """
        return self._reason_restriction

    @reason_restriction.setter
    def reason_restriction(self, reason_restriction: str):
        """Sets the reason_restriction of this BlacklistData.


        :param reason_restriction: The reason_restriction of this BlacklistData.
        :type reason_restriction: str
        """

        self._reason_restriction = reason_restriction

    @property
    def image_path(self) -> str:
        """Gets the image_path of this BlacklistData.


        :return: The image_path of this BlacklistData.
        :rtype: str
        """
        return self._image_path

    @image_path.setter
    def image_path(self, image_path: str):
        """Sets the image_path of this BlacklistData.


        :param image_path: The image_path of this BlacklistData.
        :type image_path: str
        """

        self._image_path = image_path

    @property
    def observations(self) -> str:
        """Gets the observations of this BlacklistData.


        :return: The observations of this BlacklistData.
        :rtype: str
        """
        return self._observations

    @observations.setter
    def observations(self, observations: str):
        """Sets the observations of this BlacklistData.


        :param observations: The observations of this BlacklistData.
        :type observations: str
        """

        self._observations = observations

    @property
    def user(self) -> str:
        """Gets the user of this BlacklistData.


        :return: The user of this BlacklistData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this BlacklistData.


        :param user: The user of this BlacklistData.
        :type user: str
        """

        self._user = user
