# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EmployeeMovementData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, group_business_id: int=None, employee_id: int=None, authorized_id: int=None, type_movement: str=None, observations: str=None, other_destiny: str=None, reason_out: str=None, user: str=None, name_user: str=None):  # noqa: E501
        """EmployeeMovementData - a model defined in Swagger

        :param group_business_id: The group_business_id of this EmployeeMovementData.  # noqa: E501
        :type group_business_id: int
        :param employee_id: The employee_id of this EmployeeMovementData.  # noqa: E501
        :type employee_id: int
        :param authorized_id: The authorized_id of this EmployeeMovementData.  # noqa: E501
        :type authorized_id: int
        :param type_movement: The type_movement of this EmployeeMovementData.  # noqa: E501
        :type type_movement: str
        :param observations: The observations of this EmployeeMovementData.  # noqa: E501
        :type observations: str
        :param other_destiny: The other_destiny of this EmployeeMovementData.  # noqa: E501
        :type other_destiny: str
        :param reason_out: The reason_out of this EmployeeMovementData.  # noqa: E501
        :type reason_out: str
        :param user: The user of this EmployeeMovementData.  # noqa: E501
        :type user: str
        :param name_user: The name_user of this EmployeeMovementData.  # noqa: E501
        :type name_user: str
        """
        self.swagger_types = {
            'group_business_id': int,
            'employee_id': int,
            'authorized_id': int,
            'type_movement': str,
            'observations': str,
            'other_destiny': str,
            'reason_out': str,
            'user': str,
            'name_user': str
        }

        self.attribute_map = {
            'group_business_id': 'group_business_id',
            'employee_id': 'employee_id',
            'authorized_id': 'authorized_id',
            'type_movement': 'type_movement',
            'observations': 'observations',
            'other_destiny': 'other_destiny',
            'reason_out': 'reason_out',
            'user': 'user',
            'name_user': 'name_user'
        }
        self._group_business_id = group_business_id
        self._employee_id = employee_id
        self._authorized_id = authorized_id
        self._type_movement = type_movement
        self._observations = observations
        self._other_destiny = other_destiny
        self._reason_out = reason_out
        self._user = user
        self._name_user = name_user

    @classmethod
    def from_dict(cls, dikt) -> 'EmployeeMovementData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmployeeMovementData of this EmployeeMovementData.  # noqa: E501
        :rtype: EmployeeMovementData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def group_business_id(self) -> int:
        """Gets the group_business_id of this EmployeeMovementData.


        :return: The group_business_id of this EmployeeMovementData.
        :rtype: int
        """
        return self._group_business_id

    @group_business_id.setter
    def group_business_id(self, group_business_id: int):
        """Sets the group_business_id of this EmployeeMovementData.


        :param group_business_id: The group_business_id of this EmployeeMovementData.
        :type group_business_id: int
        """

        self._group_business_id = group_business_id

    @property
    def employee_id(self) -> int:
        """Gets the employee_id of this EmployeeMovementData.


        :return: The employee_id of this EmployeeMovementData.
        :rtype: int
        """
        return self._employee_id

    @employee_id.setter
    def employee_id(self, employee_id: int):
        """Sets the employee_id of this EmployeeMovementData.


        :param employee_id: The employee_id of this EmployeeMovementData.
        :type employee_id: int
        """

        self._employee_id = employee_id

    @property
    def authorized_id(self) -> int:
        """Gets the authorized_id of this EmployeeMovementData.


        :return: The authorized_id of this EmployeeMovementData.
        :rtype: int
        """
        return self._authorized_id

    @authorized_id.setter
    def authorized_id(self, authorized_id: int):
        """Sets the authorized_id of this EmployeeMovementData.


        :param authorized_id: The authorized_id of this EmployeeMovementData.
        :type authorized_id: int
        """

        self._authorized_id = authorized_id

    @property
    def type_movement(self) -> str:
        """Gets the type_movement of this EmployeeMovementData.


        :return: The type_movement of this EmployeeMovementData.
        :rtype: str
        """
        return self._type_movement

    @type_movement.setter
    def type_movement(self, type_movement: str):
        """Sets the type_movement of this EmployeeMovementData.


        :param type_movement: The type_movement of this EmployeeMovementData.
        :type type_movement: str
        """

        self._type_movement = type_movement

    @property
    def observations(self) -> str:
        """Gets the observations of this EmployeeMovementData.


        :return: The observations of this EmployeeMovementData.
        :rtype: str
        """
        return self._observations

    @observations.setter
    def observations(self, observations: str):
        """Sets the observations of this EmployeeMovementData.


        :param observations: The observations of this EmployeeMovementData.
        :type observations: str
        """

        self._observations = observations

    @property
    def other_destiny(self) -> str:
        """Gets the other_destiny of this EmployeeMovementData.


        :return: The other_destiny of this EmployeeMovementData.
        :rtype: str
        """
        return self._other_destiny

    @other_destiny.setter
    def other_destiny(self, other_destiny: str):
        """Sets the other_destiny of this EmployeeMovementData.


        :param other_destiny: The other_destiny of this EmployeeMovementData.
        :type other_destiny: str
        """

        self._other_destiny = other_destiny

    @property
    def reason_out(self) -> str:
        """Gets the reason_out of this EmployeeMovementData.


        :return: The reason_out of this EmployeeMovementData.
        :rtype: str
        """
        return self._reason_out

    @reason_out.setter
    def reason_out(self, reason_out: str):
        """Sets the reason_out of this EmployeeMovementData.


        :param reason_out: The reason_out of this EmployeeMovementData.
        :type reason_out: str
        """

        self._reason_out = reason_out

    @property
    def user(self) -> str:
        """Gets the user of this EmployeeMovementData.


        :return: The user of this EmployeeMovementData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this EmployeeMovementData.


        :param user: The user of this EmployeeMovementData.
        :type user: str
        """

        self._user = user

    @property
    def name_user(self) -> str:
        """Gets the name_user of this EmployeeMovementData.


        :return: The name_user of this EmployeeMovementData.
        :rtype: str
        """
        return self._name_user

    @name_user.setter
    def name_user(self, name_user: str):
        """Sets the name_user of this EmployeeMovementData.


        :param name_user: The name_user of this EmployeeMovementData.
        :type name_user: str
        """

        self._name_user = name_user
