# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EmployeeInternData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_group_business: int=None, dni: str=None, names: str=None, lastname: str=None, position: str=None, observations: str=None, user: str=None, name_user: str=None, photo: List[str]=None):  # noqa: E501
        """EmployeeInternData - a model defined in Swagger

        :param id_group_business: The id_group_business of this EmployeeInternData.  # noqa: E501
        :type id_group_business: int
        :param dni: The dni of this EmployeeInternData.  # noqa: E501
        :type dni: str
        :param names: The names of this EmployeeInternData.  # noqa: E501
        :type names: str
        :param lastname: The lastname of this EmployeeInternData.  # noqa: E501
        :type lastname: str
        :param position: The position of this EmployeeInternData.  # noqa: E501
        :type position: str
        :param observations: The observations of this EmployeeInternData.  # noqa: E501
        :type observations: str
        :param user: The user of this EmployeeInternData.  # noqa: E501
        :type user: str
        :param name_user: The name_user of this EmployeeInternData.  # noqa: E501
        :type name_user: str
        :param photo: The photo of this EmployeeInternData.  # noqa: E501
        :type photo: List[str]
        """
        self.swagger_types = {
            'id_group_business': int,
            'dni': str,
            'names': str,
            'lastname': str,
            'position': str,
            'observations': str,
            'user': str,
            'name_user': str,
            'photo': List[str]
        }

        self.attribute_map = {
            'id_group_business': 'id_group_business',
            'dni': 'dni',
            'names': 'names',
            'lastname': 'lastname',
            'position': 'position',
            'observations': 'observations',
            'user': 'user',
            'name_user': 'name_user',
            'photo': 'photo'
        }
        self._id_group_business = id_group_business
        self._dni = dni
        self._names = names
        self._lastname = lastname
        self._position = position
        self._observations = observations
        self._user = user
        self._name_user = name_user
        self._photo = photo

    @classmethod
    def from_dict(cls, dikt) -> 'EmployeeInternData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmployeeInternData of this EmployeeInternData.  # noqa: E501
        :rtype: EmployeeInternData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_group_business(self) -> int:
        """Gets the id_group_business of this EmployeeInternData.


        :return: The id_group_business of this EmployeeInternData.
        :rtype: int
        """
        return self._id_group_business

    @id_group_business.setter
    def id_group_business(self, id_group_business: int):
        """Sets the id_group_business of this EmployeeInternData.


        :param id_group_business: The id_group_business of this EmployeeInternData.
        :type id_group_business: int
        """

        self._id_group_business = id_group_business

    @property
    def dni(self) -> str:
        """Gets the dni of this EmployeeInternData.


        :return: The dni of this EmployeeInternData.
        :rtype: str
        """
        return self._dni

    @dni.setter
    def dni(self, dni: str):
        """Sets the dni of this EmployeeInternData.


        :param dni: The dni of this EmployeeInternData.
        :type dni: str
        """

        self._dni = dni

    @property
    def names(self) -> str:
        """Gets the names of this EmployeeInternData.


        :return: The names of this EmployeeInternData.
        :rtype: str
        """
        return self._names

    @names.setter
    def names(self, names: str):
        """Sets the names of this EmployeeInternData.


        :param names: The names of this EmployeeInternData.
        :type names: str
        """

        self._names = names

    @property
    def lastname(self) -> str:
        """Gets the lastname of this EmployeeInternData.


        :return: The lastname of this EmployeeInternData.
        :rtype: str
        """
        return self._lastname

    @lastname.setter
    def lastname(self, lastname: str):
        """Sets the lastname of this EmployeeInternData.


        :param lastname: The lastname of this EmployeeInternData.
        :type lastname: str
        """

        self._lastname = lastname

    @property
    def position(self) -> str:
        """Gets the position of this EmployeeInternData.


        :return: The position of this EmployeeInternData.
        :rtype: str
        """
        return self._position

    @position.setter
    def position(self, position: str):
        """Sets the position of this EmployeeInternData.


        :param position: The position of this EmployeeInternData.
        :type position: str
        """

        self._position = position

    @property
    def observations(self) -> str:
        """Gets the observations of this EmployeeInternData.


        :return: The observations of this EmployeeInternData.
        :rtype: str
        """
        return self._observations

    @observations.setter
    def observations(self, observations: str):
        """Sets the observations of this EmployeeInternData.


        :param observations: The observations of this EmployeeInternData.
        :type observations: str
        """

        self._observations = observations

    @property
    def user(self) -> str:
        """Gets the user of this EmployeeInternData.


        :return: The user of this EmployeeInternData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this EmployeeInternData.


        :param user: The user of this EmployeeInternData.
        :type user: str
        """

        self._user = user

    @property
    def name_user(self) -> str:
        """Gets the name_user of this EmployeeInternData.


        :return: The name_user of this EmployeeInternData.
        :rtype: str
        """
        return self._name_user

    @name_user.setter
    def name_user(self, name_user: str):
        """Sets the name_user of this EmployeeInternData.


        :param name_user: The name_user of this EmployeeInternData.
        :type name_user: str
        """

        self._name_user = name_user

    @property
    def photo(self) -> List[str]:
        """Gets the photo of this EmployeeInternData.


        :return: The photo of this EmployeeInternData.
        :rtype: List[str]
        """
        return self._photo

    @photo.setter
    def photo(self, photo: List[str]):
        """Sets the photo of this EmployeeInternData.


        :param photo: The photo of this EmployeeInternData.
        :type photo: List[str]
        """

        self._photo = photo
