# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FormExpoData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, names: str=None, email: str=None, business: str=None, position: str=None, type_industry: str=None, is_assist: bool=None):  # noqa: E501
        """FormExpoData - a model defined in Swagger

        :param names: The names of this FormExpoData.  # noqa: E501
        :type names: str
        :param email: The email of this FormExpoData.  # noqa: E501
        :type email: str
        :param business: The business of this FormExpoData.  # noqa: E501
        :type business: str
        :param position: The position of this FormExpoData.  # noqa: E501
        :type position: str
        :param type_industry: The type_industry of this FormExpoData.  # noqa: E501
        :type type_industry: str
        :param is_assist: The is_assist of this FormExpoData.  # noqa: E501
        :type is_assist: bool
        """
        self.swagger_types = {
            'names': str,
            'email': str,
            'business': str,
            'position': str,
            'type_industry': str,
            'is_assist': bool
        }

        self.attribute_map = {
            'names': 'names',
            'email': 'email',
            'business': 'business',
            'position': 'position',
            'type_industry': 'type_industry',
            'is_assist': 'is_assist'
        }
        self._names = names
        self._email = email
        self._business = business
        self._position = position
        self._type_industry = type_industry
        self._is_assist = is_assist

    @classmethod
    def from_dict(cls, dikt) -> 'FormExpoData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FormExpoData of this FormExpoData.  # noqa: E501
        :rtype: FormExpoData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def names(self) -> str:
        """Gets the names of this FormExpoData.


        :return: The names of this FormExpoData.
        :rtype: str
        """
        return self._names

    @names.setter
    def names(self, names: str):
        """Sets the names of this FormExpoData.


        :param names: The names of this FormExpoData.
        :type names: str
        """

        self._names = names

    @property
    def email(self) -> str:
        """Gets the email of this FormExpoData.


        :return: The email of this FormExpoData.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this FormExpoData.


        :param email: The email of this FormExpoData.
        :type email: str
        """

        self._email = email

    @property
    def business(self) -> str:
        """Gets the business of this FormExpoData.


        :return: The business of this FormExpoData.
        :rtype: str
        """
        return self._business

    @business.setter
    def business(self, business: str):
        """Sets the business of this FormExpoData.


        :param business: The business of this FormExpoData.
        :type business: str
        """

        self._business = business

    @property
    def position(self) -> str:
        """Gets the position of this FormExpoData.


        :return: The position of this FormExpoData.
        :rtype: str
        """
        return self._position

    @position.setter
    def position(self, position: str):
        """Sets the position of this FormExpoData.


        :param position: The position of this FormExpoData.
        :type position: str
        """

        self._position = position

    @property
    def type_industry(self) -> str:
        """Gets the type_industry of this FormExpoData.


        :return: The type_industry of this FormExpoData.
        :rtype: str
        """
        return self._type_industry

    @type_industry.setter
    def type_industry(self, type_industry: str):
        """Sets the type_industry of this FormExpoData.


        :param type_industry: The type_industry of this FormExpoData.
        :type type_industry: str
        """

        self._type_industry = type_industry

    @property
    def is_assist(self) -> bool:
        """Gets the is_assist of this FormExpoData.


        :return: The is_assist of this FormExpoData.
        :rtype: bool
        """
        return self._is_assist

    @is_assist.setter
    def is_assist(self, is_assist: bool):
        """Sets the is_assist of this FormExpoData.


        :param is_assist: The is_assist of this FormExpoData.
        :type is_assist: bool
        """

        self._is_assist = is_assist
