# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LogBookOutData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_category: int=None, shipping_guide: str=None, id_product: int=None, quantity: float=None, weight: float=None, truck_license_plate: str=None, name_driver: str=None, person_picking_up_product: str=None, destiny: str=None, authorized_by: str=None, observations: str=None):  # noqa: E501
        """LogBookOutData - a model defined in Swagger

        :param id_category: The id_category of this LogBookOutData.  # noqa: E501
        :type id_category: int
        :param shipping_guide: The shipping_guide of this LogBookOutData.  # noqa: E501
        :type shipping_guide: str
        :param id_product: The id_product of this LogBookOutData.  # noqa: E501
        :type id_product: int
        :param quantity: The quantity of this LogBookOutData.  # noqa: E501
        :type quantity: float
        :param weight: The weight of this LogBookOutData.  # noqa: E501
        :type weight: float
        :param truck_license_plate: The truck_license_plate of this LogBookOutData.  # noqa: E501
        :type truck_license_plate: str
        :param name_driver: The name_driver of this LogBookOutData.  # noqa: E501
        :type name_driver: str
        :param person_picking_up_product: The person_picking_up_product of this LogBookOutData.  # noqa: E501
        :type person_picking_up_product: str
        :param destiny: The destiny of this LogBookOutData.  # noqa: E501
        :type destiny: str
        :param authorized_by: The authorized_by of this LogBookOutData.  # noqa: E501
        :type authorized_by: str
        :param observations: The observations of this LogBookOutData.  # noqa: E501
        :type observations: str
        """
        self.swagger_types = {
            'id_category': int,
            'shipping_guide': str,
            'id_product': int,
            'quantity': float,
            'weight': float,
            'truck_license_plate': str,
            'name_driver': str,
            'person_picking_up_product': str,
            'destiny': str,
            'authorized_by': str,
            'observations': str
        }

        self.attribute_map = {
            'id_category': 'id_category',
            'shipping_guide': 'shipping_guide',
            'id_product': 'id_product',
            'quantity': 'quantity',
            'weight': 'weight',
            'truck_license_plate': 'truck_license_plate',
            'name_driver': 'name_driver',
            'person_picking_up_product': 'person_picking_up_product',
            'destiny': 'destiny',
            'authorized_by': 'authorized_by',
            'observations': 'observations'
        }
        self._id_category = id_category
        self._shipping_guide = shipping_guide
        self._id_product = id_product
        self._quantity = quantity
        self._weight = weight
        self._truck_license_plate = truck_license_plate
        self._name_driver = name_driver
        self._person_picking_up_product = person_picking_up_product
        self._destiny = destiny
        self._authorized_by = authorized_by
        self._observations = observations

    @classmethod
    def from_dict(cls, dikt) -> 'LogBookOutData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LogBookOutData of this LogBookOutData.  # noqa: E501
        :rtype: LogBookOutData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_category(self) -> int:
        """Gets the id_category of this LogBookOutData.


        :return: The id_category of this LogBookOutData.
        :rtype: int
        """
        return self._id_category

    @id_category.setter
    def id_category(self, id_category: int):
        """Sets the id_category of this LogBookOutData.


        :param id_category: The id_category of this LogBookOutData.
        :type id_category: int
        """

        self._id_category = id_category

    @property
    def shipping_guide(self) -> str:
        """Gets the shipping_guide of this LogBookOutData.


        :return: The shipping_guide of this LogBookOutData.
        :rtype: str
        """
        return self._shipping_guide

    @shipping_guide.setter
    def shipping_guide(self, shipping_guide: str):
        """Sets the shipping_guide of this LogBookOutData.


        :param shipping_guide: The shipping_guide of this LogBookOutData.
        :type shipping_guide: str
        """

        self._shipping_guide = shipping_guide

    @property
    def id_product(self) -> int:
        """Gets the id_product of this LogBookOutData.


        :return: The id_product of this LogBookOutData.
        :rtype: int
        """
        return self._id_product

    @id_product.setter
    def id_product(self, id_product: int):
        """Sets the id_product of this LogBookOutData.


        :param id_product: The id_product of this LogBookOutData.
        :type id_product: int
        """

        self._id_product = id_product

    @property
    def quantity(self) -> float:
        """Gets the quantity of this LogBookOutData.


        :return: The quantity of this LogBookOutData.
        :rtype: float
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: float):
        """Sets the quantity of this LogBookOutData.


        :param quantity: The quantity of this LogBookOutData.
        :type quantity: float
        """

        self._quantity = quantity

    @property
    def weight(self) -> float:
        """Gets the weight of this LogBookOutData.


        :return: The weight of this LogBookOutData.
        :rtype: float
        """
        return self._weight

    @weight.setter
    def weight(self, weight: float):
        """Sets the weight of this LogBookOutData.


        :param weight: The weight of this LogBookOutData.
        :type weight: float
        """

        self._weight = weight

    @property
    def truck_license_plate(self) -> str:
        """Gets the truck_license_plate of this LogBookOutData.


        :return: The truck_license_plate of this LogBookOutData.
        :rtype: str
        """
        return self._truck_license_plate

    @truck_license_plate.setter
    def truck_license_plate(self, truck_license_plate: str):
        """Sets the truck_license_plate of this LogBookOutData.


        :param truck_license_plate: The truck_license_plate of this LogBookOutData.
        :type truck_license_plate: str
        """

        self._truck_license_plate = truck_license_plate

    @property
    def name_driver(self) -> str:
        """Gets the name_driver of this LogBookOutData.


        :return: The name_driver of this LogBookOutData.
        :rtype: str
        """
        return self._name_driver

    @name_driver.setter
    def name_driver(self, name_driver: str):
        """Sets the name_driver of this LogBookOutData.


        :param name_driver: The name_driver of this LogBookOutData.
        :type name_driver: str
        """

        self._name_driver = name_driver

    @property
    def person_picking_up_product(self) -> str:
        """Gets the person_picking_up_product of this LogBookOutData.


        :return: The person_picking_up_product of this LogBookOutData.
        :rtype: str
        """
        return self._person_picking_up_product

    @person_picking_up_product.setter
    def person_picking_up_product(self, person_picking_up_product: str):
        """Sets the person_picking_up_product of this LogBookOutData.


        :param person_picking_up_product: The person_picking_up_product of this LogBookOutData.
        :type person_picking_up_product: str
        """

        self._person_picking_up_product = person_picking_up_product

    @property
    def destiny(self) -> str:
        """Gets the destiny of this LogBookOutData.


        :return: The destiny of this LogBookOutData.
        :rtype: str
        """
        return self._destiny

    @destiny.setter
    def destiny(self, destiny: str):
        """Sets the destiny of this LogBookOutData.


        :param destiny: The destiny of this LogBookOutData.
        :type destiny: str
        """

        self._destiny = destiny

    @property
    def authorized_by(self) -> str:
        """Gets the authorized_by of this LogBookOutData.


        :return: The authorized_by of this LogBookOutData.
        :rtype: str
        """
        return self._authorized_by

    @authorized_by.setter
    def authorized_by(self, authorized_by: str):
        """Sets the authorized_by of this LogBookOutData.


        :param authorized_by: The authorized_by of this LogBookOutData.
        :type authorized_by: str
        """

        self._authorized_by = authorized_by

    @property
    def observations(self) -> str:
        """Gets the observations of this LogBookOutData.


        :return: The observations of this LogBookOutData.
        :rtype: str
        """
        return self._observations

    @observations.setter
    def observations(self, observations: str):
        """Sets the observations of this LogBookOutData.


        :param observations: The observations of this LogBookOutData.
        :type observations: str
        """

        self._observations = observations
