# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LogBookEntryData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_category: int=None, shipping_guide: str=None, description: str=None, quantity: float=None, id_unity: int=None, weight: float=None, provider: str=None, destiny_intern: str=None, authorized_by: str=None, observations: str=None, created_by: str=None):  # noqa: E501
        """LogBookEntryData - a model defined in Swagger

        :param id_category: The id_category of this LogBookEntryData.  # noqa: E501
        :type id_category: int
        :param shipping_guide: The shipping_guide of this LogBookEntryData.  # noqa: E501
        :type shipping_guide: str
        :param description: The description of this LogBookEntryData.  # noqa: E501
        :type description: str
        :param quantity: The quantity of this LogBookEntryData.  # noqa: E501
        :type quantity: float
        :param id_unity: The id_unity of this LogBookEntryData.  # noqa: E501
        :type id_unity: int
        :param weight: The weight of this LogBookEntryData.  # noqa: E501
        :type weight: float
        :param provider: The provider of this LogBookEntryData.  # noqa: E501
        :type provider: str
        :param destiny_intern: The destiny_intern of this LogBookEntryData.  # noqa: E501
        :type destiny_intern: str
        :param authorized_by: The authorized_by of this LogBookEntryData.  # noqa: E501
        :type authorized_by: str
        :param observations: The observations of this LogBookEntryData.  # noqa: E501
        :type observations: str
        :param created_by: The created_by of this LogBookEntryData.  # noqa: E501
        :type created_by: str
        """
        self.swagger_types = {
            'id_category': int,
            'shipping_guide': str,
            'description': str,
            'quantity': float,
            'id_unity': int,
            'weight': float,
            'provider': str,
            'destiny_intern': str,
            'authorized_by': str,
            'observations': str,
            'created_by': str
        }

        self.attribute_map = {
            'id_category': 'id_category',
            'shipping_guide': 'shipping_guide',
            'description': 'description',
            'quantity': 'quantity',
            'id_unity': 'id_unity',
            'weight': 'weight',
            'provider': 'provider',
            'destiny_intern': 'destiny_intern',
            'authorized_by': 'authorized_by',
            'observations': 'observations',
            'created_by': 'created_by'
        }
        self._id_category = id_category
        self._shipping_guide = shipping_guide
        self._description = description
        self._quantity = quantity
        self._id_unity = id_unity
        self._weight = weight
        self._provider = provider
        self._destiny_intern = destiny_intern
        self._authorized_by = authorized_by
        self._observations = observations
        self._created_by = created_by

    @classmethod
    def from_dict(cls, dikt) -> 'LogBookEntryData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LogBookEntryData of this LogBookEntryData.  # noqa: E501
        :rtype: LogBookEntryData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_category(self) -> int:
        """Gets the id_category of this LogBookEntryData.


        :return: The id_category of this LogBookEntryData.
        :rtype: int
        """
        return self._id_category

    @id_category.setter
    def id_category(self, id_category: int):
        """Sets the id_category of this LogBookEntryData.


        :param id_category: The id_category of this LogBookEntryData.
        :type id_category: int
        """

        self._id_category = id_category

    @property
    def shipping_guide(self) -> str:
        """Gets the shipping_guide of this LogBookEntryData.


        :return: The shipping_guide of this LogBookEntryData.
        :rtype: str
        """
        return self._shipping_guide

    @shipping_guide.setter
    def shipping_guide(self, shipping_guide: str):
        """Sets the shipping_guide of this LogBookEntryData.


        :param shipping_guide: The shipping_guide of this LogBookEntryData.
        :type shipping_guide: str
        """

        self._shipping_guide = shipping_guide

    @property
    def description(self) -> str:
        """Gets the description of this LogBookEntryData.


        :return: The description of this LogBookEntryData.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this LogBookEntryData.


        :param description: The description of this LogBookEntryData.
        :type description: str
        """

        self._description = description

    @property
    def quantity(self) -> float:
        """Gets the quantity of this LogBookEntryData.


        :return: The quantity of this LogBookEntryData.
        :rtype: float
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: float):
        """Sets the quantity of this LogBookEntryData.


        :param quantity: The quantity of this LogBookEntryData.
        :type quantity: float
        """

        self._quantity = quantity

    @property
    def id_unity(self) -> int:
        """Gets the id_unity of this LogBookEntryData.


        :return: The id_unity of this LogBookEntryData.
        :rtype: int
        """
        return self._id_unity

    @id_unity.setter
    def id_unity(self, id_unity: int):
        """Sets the id_unity of this LogBookEntryData.


        :param id_unity: The id_unity of this LogBookEntryData.
        :type id_unity: int
        """

        self._id_unity = id_unity

    @property
    def weight(self) -> float:
        """Gets the weight of this LogBookEntryData.


        :return: The weight of this LogBookEntryData.
        :rtype: float
        """
        return self._weight

    @weight.setter
    def weight(self, weight: float):
        """Sets the weight of this LogBookEntryData.


        :param weight: The weight of this LogBookEntryData.
        :type weight: float
        """

        self._weight = weight

    @property
    def provider(self) -> str:
        """Gets the provider of this LogBookEntryData.


        :return: The provider of this LogBookEntryData.
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider: str):
        """Sets the provider of this LogBookEntryData.


        :param provider: The provider of this LogBookEntryData.
        :type provider: str
        """

        self._provider = provider

    @property
    def destiny_intern(self) -> str:
        """Gets the destiny_intern of this LogBookEntryData.


        :return: The destiny_intern of this LogBookEntryData.
        :rtype: str
        """
        return self._destiny_intern

    @destiny_intern.setter
    def destiny_intern(self, destiny_intern: str):
        """Sets the destiny_intern of this LogBookEntryData.


        :param destiny_intern: The destiny_intern of this LogBookEntryData.
        :type destiny_intern: str
        """

        self._destiny_intern = destiny_intern

    @property
    def authorized_by(self) -> str:
        """Gets the authorized_by of this LogBookEntryData.


        :return: The authorized_by of this LogBookEntryData.
        :rtype: str
        """
        return self._authorized_by

    @authorized_by.setter
    def authorized_by(self, authorized_by: str):
        """Sets the authorized_by of this LogBookEntryData.


        :param authorized_by: The authorized_by of this LogBookEntryData.
        :type authorized_by: str
        """

        self._authorized_by = authorized_by

    @property
    def observations(self) -> str:
        """Gets the observations of this LogBookEntryData.


        :return: The observations of this LogBookEntryData.
        :rtype: str
        """
        return self._observations

    @observations.setter
    def observations(self, observations: str):
        """Sets the observations of this LogBookEntryData.


        :param observations: The observations of this LogBookEntryData.
        :type observations: str
        """

        self._observations = observations

    @property
    def created_by(self) -> str:
        """Gets the created_by of this LogBookEntryData.


        :return: The created_by of this LogBookEntryData.
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by: str):
        """Sets the created_by of this LogBookEntryData.


        :param created_by: The created_by of this LogBookEntryData.
        :type created_by: str
        """

        self._created_by = created_by
