# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LogBookOutData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_group_business: int=None, id_category: int=None, id_unity: int=None, shipping_guide: str=None, quantity: float=None, weight: float=None, truck_license: str=None, name_driver: str=None, person_withdraws: str=None, destiny: str=None, authorized_by: str=None, observations: str=None, created_by: str=None):  # noqa: E501
        """LogBookOutData - a model defined in Swagger

        :param id_group_business: The id_group_business of this LogBookOutData.  # noqa: E501
        :type id_group_business: int
        :param id_category: The id_category of this LogBookOutData.  # noqa: E501
        :type id_category: int
        :param id_unity: The id_unity of this LogBookOutData.  # noqa: E501
        :type id_unity: int
        :param shipping_guide: The shipping_guide of this LogBookOutData.  # noqa: E501
        :type shipping_guide: str
        :param quantity: The quantity of this LogBookOutData.  # noqa: E501
        :type quantity: float
        :param weight: The weight of this LogBookOutData.  # noqa: E501
        :type weight: float
        :param truck_license: The truck_license of this LogBookOutData.  # noqa: E501
        :type truck_license: str
        :param name_driver: The name_driver of this LogBookOutData.  # noqa: E501
        :type name_driver: str
        :param person_withdraws: The person_withdraws of this LogBookOutData.  # noqa: E501
        :type person_withdraws: str
        :param destiny: The destiny of this LogBookOutData.  # noqa: E501
        :type destiny: str
        :param authorized_by: The authorized_by of this LogBookOutData.  # noqa: E501
        :type authorized_by: str
        :param observations: The observations of this LogBookOutData.  # noqa: E501
        :type observations: str
        :param created_by: The created_by of this LogBookOutData.  # noqa: E501
        :type created_by: str
        """
        self.swagger_types = {
            'id_group_business': int,
            'id_category': int,
            'id_unity': int,
            'shipping_guide': str,
            'quantity': float,
            'weight': float,
            'truck_license': str,
            'name_driver': str,
            'person_withdraws': str,
            'destiny': str,
            'authorized_by': str,
            'observations': str,
            'created_by': str
        }

        self.attribute_map = {
            'id_group_business': 'id_group_business',
            'id_category': 'id_category',
            'id_unity': 'id_unity',
            'shipping_guide': 'shipping_guide',
            'quantity': 'quantity',
            'weight': 'weight',
            'truck_license': 'truck_license',
            'name_driver': 'name_driver',
            'person_withdraws': 'person_withdraws',
            'destiny': 'destiny',
            'authorized_by': 'authorized_by',
            'observations': 'observations',
            'created_by': 'created_by'
        }
        self._id_group_business = id_group_business
        self._id_category = id_category
        self._id_unity = id_unity
        self._shipping_guide = shipping_guide
        self._quantity = quantity
        self._weight = weight
        self._truck_license = truck_license
        self._name_driver = name_driver
        self._person_withdraws = person_withdraws
        self._destiny = destiny
        self._authorized_by = authorized_by
        self._observations = observations
        self._created_by = created_by

    @classmethod
    def from_dict(cls, dikt) -> 'LogBookOutData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LogBookOutData of this LogBookOutData.  # noqa: E501
        :rtype: LogBookOutData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_group_business(self) -> int:
        """Gets the id_group_business of this LogBookOutData.


        :return: The id_group_business of this LogBookOutData.
        :rtype: int
        """
        return self._id_group_business

    @id_group_business.setter
    def id_group_business(self, id_group_business: int):
        """Sets the id_group_business of this LogBookOutData.


        :param id_group_business: The id_group_business of this LogBookOutData.
        :type id_group_business: int
        """

        self._id_group_business = id_group_business

    @property
    def id_category(self) -> int:
        """Gets the id_category of this LogBookOutData.


        :return: The id_category of this LogBookOutData.
        :rtype: int
        """
        return self._id_category

    @id_category.setter
    def id_category(self, id_category: int):
        """Sets the id_category of this LogBookOutData.


        :param id_category: The id_category of this LogBookOutData.
        :type id_category: int
        """

        self._id_category = id_category

    @property
    def id_unity(self) -> int:
        """Gets the id_unity of this LogBookOutData.


        :return: The id_unity of this LogBookOutData.
        :rtype: int
        """
        return self._id_unity

    @id_unity.setter
    def id_unity(self, id_unity: int):
        """Sets the id_unity of this LogBookOutData.


        :param id_unity: The id_unity of this LogBookOutData.
        :type id_unity: int
        """

        self._id_unity = id_unity

    @property
    def shipping_guide(self) -> str:
        """Gets the shipping_guide of this LogBookOutData.


        :return: The shipping_guide of this LogBookOutData.
        :rtype: str
        """
        return self._shipping_guide

    @shipping_guide.setter
    def shipping_guide(self, shipping_guide: str):
        """Sets the shipping_guide of this LogBookOutData.


        :param shipping_guide: The shipping_guide of this LogBookOutData.
        :type shipping_guide: str
        """

        self._shipping_guide = shipping_guide

    @property
    def quantity(self) -> float:
        """Gets the quantity of this LogBookOutData.


        :return: The quantity of this LogBookOutData.
        :rtype: float
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: float):
        """Sets the quantity of this LogBookOutData.


        :param quantity: The quantity of this LogBookOutData.
        :type quantity: float
        """

        self._quantity = quantity

    @property
    def weight(self) -> float:
        """Gets the weight of this LogBookOutData.


        :return: The weight of this LogBookOutData.
        :rtype: float
        """
        return self._weight

    @weight.setter
    def weight(self, weight: float):
        """Sets the weight of this LogBookOutData.


        :param weight: The weight of this LogBookOutData.
        :type weight: float
        """

        self._weight = weight

    @property
    def truck_license(self) -> str:
        """Gets the truck_license of this LogBookOutData.


        :return: The truck_license of this LogBookOutData.
        :rtype: str
        """
        return self._truck_license

    @truck_license.setter
    def truck_license(self, truck_license: str):
        """Sets the truck_license of this LogBookOutData.


        :param truck_license: The truck_license of this LogBookOutData.
        :type truck_license: str
        """

        self._truck_license = truck_license

    @property
    def name_driver(self) -> str:
        """Gets the name_driver of this LogBookOutData.


        :return: The name_driver of this LogBookOutData.
        :rtype: str
        """
        return self._name_driver

    @name_driver.setter
    def name_driver(self, name_driver: str):
        """Sets the name_driver of this LogBookOutData.


        :param name_driver: The name_driver of this LogBookOutData.
        :type name_driver: str
        """

        self._name_driver = name_driver

    @property
    def person_withdraws(self) -> str:
        """Gets the person_withdraws of this LogBookOutData.


        :return: The person_withdraws of this LogBookOutData.
        :rtype: str
        """
        return self._person_withdraws

    @person_withdraws.setter
    def person_withdraws(self, person_withdraws: str):
        """Sets the person_withdraws of this LogBookOutData.


        :param person_withdraws: The person_withdraws of this LogBookOutData.
        :type person_withdraws: str
        """

        self._person_withdraws = person_withdraws

    @property
    def destiny(self) -> str:
        """Gets the destiny of this LogBookOutData.


        :return: The destiny of this LogBookOutData.
        :rtype: str
        """
        return self._destiny

    @destiny.setter
    def destiny(self, destiny: str):
        """Sets the destiny of this LogBookOutData.


        :param destiny: The destiny of this LogBookOutData.
        :type destiny: str
        """

        self._destiny = destiny

    @property
    def authorized_by(self) -> str:
        """Gets the authorized_by of this LogBookOutData.


        :return: The authorized_by of this LogBookOutData.
        :rtype: str
        """
        return self._authorized_by

    @authorized_by.setter
    def authorized_by(self, authorized_by: str):
        """Sets the authorized_by of this LogBookOutData.


        :param authorized_by: The authorized_by of this LogBookOutData.
        :type authorized_by: str
        """

        self._authorized_by = authorized_by

    @property
    def observations(self) -> str:
        """Gets the observations of this LogBookOutData.


        :return: The observations of this LogBookOutData.
        :rtype: str
        """
        return self._observations

    @observations.setter
    def observations(self, observations: str):
        """Sets the observations of this LogBookOutData.


        :param observations: The observations of this LogBookOutData.
        :type observations: str
        """

        self._observations = observations

    @property
    def created_by(self) -> str:
        """Gets the created_by of this LogBookOutData.


        :return: The created_by of this LogBookOutData.
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by: str):
        """Sets the created_by of this LogBookOutData.


        :param created_by: The created_by of this LogBookOutData.
        :type created_by: str
        """

        self._created_by = created_by
