# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LoginData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user: str=None, password: str=None, project_id: int=None, fcm_token: str=None, platform: str=None):  # noqa: E501
        """LoginData - a model defined in Swagger

        :param user: The user of this LoginData.  # noqa: E501
        :type user: str
        :param password: The password of this LoginData.  # noqa: E501
        :type password: str
        :param project_id: The project_id of this LoginData.  # noqa: E501
        :type project_id: int
        :param fcm_token: The fcm_token of this LoginData.  # noqa: E501
        :type fcm_token: str
        :param platform: The platform of this LoginData.  # noqa: E501
        :type platform: str
        """
        self.swagger_types = {
            'user': str,
            'password': str,
            'project_id': int,
            'fcm_token': str,
            'platform': str
        }

        self.attribute_map = {
            'user': 'user',
            'password': 'password',
            'project_id': 'project_id',
            'fcm_token': 'fcm_token',
            'platform': 'platform'
        }
        self._user = user
        self._password = password
        self._project_id = project_id
        self._fcm_token = fcm_token
        self._platform = platform

    @classmethod
    def from_dict(cls, dikt) -> 'LoginData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginData of this LoginData.  # noqa: E501
        :rtype: LoginData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> str:
        """Gets the user of this LoginData.


        :return: The user of this LoginData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this LoginData.


        :param user: The user of this LoginData.
        :type user: str
        """

        self._user = user

    @property
    def password(self) -> str:
        """Gets the password of this LoginData.


        :return: The password of this LoginData.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this LoginData.


        :param password: The password of this LoginData.
        :type password: str
        """

        self._password = password

    @property
    def project_id(self) -> int:
        """Gets the project_id of this LoginData.


        :return: The project_id of this LoginData.
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id: int):
        """Sets the project_id of this LoginData.


        :param project_id: The project_id of this LoginData.
        :type project_id: int
        """

        self._project_id = project_id

    @property
    def fcm_token(self) -> str:
        """Gets the fcm_token of this LoginData.


        :return: The fcm_token of this LoginData.
        :rtype: str
        """
        return self._fcm_token

    @fcm_token.setter
    def fcm_token(self, fcm_token: str):
        """Sets the fcm_token of this LoginData.


        :param fcm_token: The fcm_token of this LoginData.
        :type fcm_token: str
        """

        self._fcm_token = fcm_token

    @property
    def platform(self) -> str:
        """Gets the platform of this LoginData.


        :return: The platform of this LoginData.
        :rtype: str
        """
        return self._platform

    @platform.setter
    def platform(self, platform: str):
        """Sets the platform of this LoginData.


        :param platform: The platform of this LoginData.
        :type platform: str
        """

        self._platform = platform
