# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LoginData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user: str=None, password: str=None):  # noqa: E501
        """LoginData - a model defined in Swagger

        :param user: The user of this LoginData.  # noqa: E501
        :type user: str
        :param password: The password of this LoginData.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'user': str,
            'password': str
        }

        self.attribute_map = {
            'user': 'user',
            'password': 'password'
        }
        self._user = user
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'LoginData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginData of this LoginData.  # noqa: E501
        :rtype: LoginData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> str:
        """Gets the user of this LoginData.


        :return: The user of this LoginData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this LoginData.


        :param user: The user of this LoginData.
        :type user: str
        """

        self._user = user

    @property
    def password(self) -> str:
        """Gets the password of this LoginData.


        :return: The password of this LoginData.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this LoginData.


        :param password: The password of this LoginData.
        :type password: str
        """

        self._password = password
