# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LogoutData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user: str=None, token: str=None):  # noqa: E501
        """LogoutData - a model defined in Swagger

        :param user: The user of this LogoutData.  # noqa: E501
        :type user: str
        :param token: The token of this LogoutData.  # noqa: E501
        :type token: str
        """
        self.swagger_types = {
            'user': str,
            'token': str
        }

        self.attribute_map = {
            'user': 'user',
            'token': 'token'
        }
        self._user = user
        self._token = token

    @classmethod
    def from_dict(cls, dikt) -> 'LogoutData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LogoutData of this LogoutData.  # noqa: E501
        :rtype: LogoutData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> str:
        """Gets the user of this LogoutData.


        :return: The user of this LogoutData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this LogoutData.


        :param user: The user of this LogoutData.
        :type user: str
        """

        self._user = user

    @property
    def token(self) -> str:
        """Gets the token of this LogoutData.


        :return: The token of this LogoutData.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this LogoutData.


        :param token: The token of this LogoutData.
        :type token: str
        """

        self._token = token
