# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NewUserData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user: str=None, email: str=None, password: str=None, attributes: object=None, role_id: str=None):  # noqa: E501
        """NewUserData - a model defined in Swagger

        :param user: The user of this NewUserData.  # noqa: E501
        :type user: str
        :param email: The email of this NewUserData.  # noqa: E501
        :type email: str
        :param password: The password of this NewUserData.  # noqa: E501
        :type password: str
        :param attributes: The attributes of this NewUserData.  # noqa: E501
        :type attributes: object
        :param role_id: The role_id of this NewUserData.  # noqa: E501
        :type role_id: str
        """
        self.swagger_types = {
            'user': str,
            'email': str,
            'password': str,
            'attributes': object,
            'role_id': str
        }

        self.attribute_map = {
            'user': 'user',
            'email': 'email',
            'password': 'password',
            'attributes': 'attributes',
            'role_id': 'role_id'
        }
        self._user = user
        self._email = email
        self._password = password
        self._attributes = attributes
        self._role_id = role_id

    @classmethod
    def from_dict(cls, dikt) -> 'NewUserData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewUserData of this NewUserData.  # noqa: E501
        :rtype: NewUserData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> str:
        """Gets the user of this NewUserData.


        :return: The user of this NewUserData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this NewUserData.


        :param user: The user of this NewUserData.
        :type user: str
        """

        self._user = user

    @property
    def email(self) -> str:
        """Gets the email of this NewUserData.


        :return: The email of this NewUserData.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this NewUserData.


        :param email: The email of this NewUserData.
        :type email: str
        """

        self._email = email

    @property
    def password(self) -> str:
        """Gets the password of this NewUserData.


        :return: The password of this NewUserData.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this NewUserData.


        :param password: The password of this NewUserData.
        :type password: str
        """

        self._password = password

    @property
    def attributes(self) -> object:
        """Gets the attributes of this NewUserData.


        :return: The attributes of this NewUserData.
        :rtype: object
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: object):
        """Sets the attributes of this NewUserData.


        :param attributes: The attributes of this NewUserData.
        :type attributes: object
        """

        self._attributes = attributes

    @property
    def role_id(self) -> str:
        """Gets the role_id of this NewUserData.


        :return: The role_id of this NewUserData.
        :rtype: str
        """
        return self._role_id

    @role_id.setter
    def role_id(self, role_id: str):
        """Sets the role_id of this NewUserData.


        :param role_id: The role_id of this NewUserData.
        :type role_id: str
        """

        self._role_id = role_id
