# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OrderReceiptsData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, purchase_order_id: int=None, dni_driver: str=None, truck_license: str=None, driver: str=None, quantity: int=None, user: str=None, images: List[str]=None):  # noqa: E501
        """OrderReceiptsData - a model defined in Swagger

        :param purchase_order_id: The purchase_order_id of this OrderReceiptsData.  # noqa: E501
        :type purchase_order_id: int
        :param dni_driver: The dni_driver of this OrderReceiptsData.  # noqa: E501
        :type dni_driver: str
        :param truck_license: The truck_license of this OrderReceiptsData.  # noqa: E501
        :type truck_license: str
        :param driver: The driver of this OrderReceiptsData.  # noqa: E501
        :type driver: str
        :param quantity: The quantity of this OrderReceiptsData.  # noqa: E501
        :type quantity: int
        :param user: The user of this OrderReceiptsData.  # noqa: E501
        :type user: str
        :param images: The images of this OrderReceiptsData.  # noqa: E501
        :type images: List[str]
        """
        self.swagger_types = {
            'purchase_order_id': int,
            'dni_driver': str,
            'truck_license': str,
            'driver': str,
            'quantity': int,
            'user': str,
            'images': List[str]
        }

        self.attribute_map = {
            'purchase_order_id': 'purchase_order_id',
            'dni_driver': 'dni_driver',
            'truck_license': 'truck_license',
            'driver': 'driver',
            'quantity': 'quantity',
            'user': 'user',
            'images': 'images'
        }
        self._purchase_order_id = purchase_order_id
        self._dni_driver = dni_driver
        self._truck_license = truck_license
        self._driver = driver
        self._quantity = quantity
        self._user = user
        self._images = images

    @classmethod
    def from_dict(cls, dikt) -> 'OrderReceiptsData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OrderReceiptsData of this OrderReceiptsData.  # noqa: E501
        :rtype: OrderReceiptsData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def purchase_order_id(self) -> int:
        """Gets the purchase_order_id of this OrderReceiptsData.


        :return: The purchase_order_id of this OrderReceiptsData.
        :rtype: int
        """
        return self._purchase_order_id

    @purchase_order_id.setter
    def purchase_order_id(self, purchase_order_id: int):
        """Sets the purchase_order_id of this OrderReceiptsData.


        :param purchase_order_id: The purchase_order_id of this OrderReceiptsData.
        :type purchase_order_id: int
        """

        self._purchase_order_id = purchase_order_id

    @property
    def dni_driver(self) -> str:
        """Gets the dni_driver of this OrderReceiptsData.


        :return: The dni_driver of this OrderReceiptsData.
        :rtype: str
        """
        return self._dni_driver

    @dni_driver.setter
    def dni_driver(self, dni_driver: str):
        """Sets the dni_driver of this OrderReceiptsData.


        :param dni_driver: The dni_driver of this OrderReceiptsData.
        :type dni_driver: str
        """

        self._dni_driver = dni_driver

    @property
    def truck_license(self) -> str:
        """Gets the truck_license of this OrderReceiptsData.


        :return: The truck_license of this OrderReceiptsData.
        :rtype: str
        """
        return self._truck_license

    @truck_license.setter
    def truck_license(self, truck_license: str):
        """Sets the truck_license of this OrderReceiptsData.


        :param truck_license: The truck_license of this OrderReceiptsData.
        :type truck_license: str
        """

        self._truck_license = truck_license

    @property
    def driver(self) -> str:
        """Gets the driver of this OrderReceiptsData.


        :return: The driver of this OrderReceiptsData.
        :rtype: str
        """
        return self._driver

    @driver.setter
    def driver(self, driver: str):
        """Sets the driver of this OrderReceiptsData.


        :param driver: The driver of this OrderReceiptsData.
        :type driver: str
        """

        self._driver = driver

    @property
    def quantity(self) -> int:
        """Gets the quantity of this OrderReceiptsData.


        :return: The quantity of this OrderReceiptsData.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this OrderReceiptsData.


        :param quantity: The quantity of this OrderReceiptsData.
        :type quantity: int
        """

        self._quantity = quantity

    @property
    def user(self) -> str:
        """Gets the user of this OrderReceiptsData.


        :return: The user of this OrderReceiptsData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this OrderReceiptsData.


        :param user: The user of this OrderReceiptsData.
        :type user: str
        """

        self._user = user

    @property
    def images(self) -> List[str]:
        """Gets the images of this OrderReceiptsData.


        :return: The images of this OrderReceiptsData.
        :rtype: List[str]
        """
        return self._images

    @images.setter
    def images(self, images: List[str]):
        """Sets the images of this OrderReceiptsData.


        :param images: The images of this OrderReceiptsData.
        :type images: List[str]
        """

        self._images = images
