# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OrderReceiptsData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, purchase_order_id: int=None, quantity: int=None, user: str=None):  # noqa: E501
        """OrderReceiptsData - a model defined in Swagger

        :param purchase_order_id: The purchase_order_id of this OrderReceiptsData.  # noqa: E501
        :type purchase_order_id: int
        :param quantity: The quantity of this OrderReceiptsData.  # noqa: E501
        :type quantity: int
        :param user: The user of this OrderReceiptsData.  # noqa: E501
        :type user: str
        """
        self.swagger_types = {
            'purchase_order_id': int,
            'quantity': int,
            'user': str
        }

        self.attribute_map = {
            'purchase_order_id': 'purchase_order_id',
            'quantity': 'quantity',
            'user': 'user'
        }
        self._purchase_order_id = purchase_order_id
        self._quantity = quantity
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'OrderReceiptsData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OrderReceiptsData of this OrderReceiptsData.  # noqa: E501
        :rtype: OrderReceiptsData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def purchase_order_id(self) -> int:
        """Gets the purchase_order_id of this OrderReceiptsData.


        :return: The purchase_order_id of this OrderReceiptsData.
        :rtype: int
        """
        return self._purchase_order_id

    @purchase_order_id.setter
    def purchase_order_id(self, purchase_order_id: int):
        """Sets the purchase_order_id of this OrderReceiptsData.


        :param purchase_order_id: The purchase_order_id of this OrderReceiptsData.
        :type purchase_order_id: int
        """

        self._purchase_order_id = purchase_order_id

    @property
    def quantity(self) -> int:
        """Gets the quantity of this OrderReceiptsData.


        :return: The quantity of this OrderReceiptsData.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this OrderReceiptsData.


        :param quantity: The quantity of this OrderReceiptsData.
        :type quantity: int
        """

        self._quantity = quantity

    @property
    def user(self) -> str:
        """Gets the user of this OrderReceiptsData.


        :return: The user of this OrderReceiptsData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this OrderReceiptsData.


        :param user: The user of this OrderReceiptsData.
        :type user: str
        """

        self._user = user
