# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PurchaseOrderData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, start_date: object=None, end_date: object=None, type_order: str=None, destiny_id: int=None, number_order: str=None, quantity: int=None, provider: str=None, observations: str=None, user: str=None):  # noqa: E501
        """PurchaseOrderData - a model defined in Swagger

        :param start_date: The start_date of this PurchaseOrderData.  # noqa: E501
        :type start_date: object
        :param end_date: The end_date of this PurchaseOrderData.  # noqa: E501
        :type end_date: object
        :param type_order: The type_order of this PurchaseOrderData.  # noqa: E501
        :type type_order: str
        :param destiny_id: The destiny_id of this PurchaseOrderData.  # noqa: E501
        :type destiny_id: int
        :param number_order: The number_order of this PurchaseOrderData.  # noqa: E501
        :type number_order: str
        :param quantity: The quantity of this PurchaseOrderData.  # noqa: E501
        :type quantity: int
        :param provider: The provider of this PurchaseOrderData.  # noqa: E501
        :type provider: str
        :param observations: The observations of this PurchaseOrderData.  # noqa: E501
        :type observations: str
        :param user: The user of this PurchaseOrderData.  # noqa: E501
        :type user: str
        """
        self.swagger_types = {
            'start_date': object,
            'end_date': object,
            'type_order': str,
            'destiny_id': int,
            'number_order': str,
            'quantity': int,
            'provider': str,
            'observations': str,
            'user': str
        }

        self.attribute_map = {
            'start_date': 'start_date',
            'end_date': 'end_date',
            'type_order': 'type_order',
            'destiny_id': 'destiny_id',
            'number_order': 'number_order',
            'quantity': 'quantity',
            'provider': 'provider',
            'observations': 'observations',
            'user': 'user'
        }
        self._start_date = start_date
        self._end_date = end_date
        self._type_order = type_order
        self._destiny_id = destiny_id
        self._number_order = number_order
        self._quantity = quantity
        self._provider = provider
        self._observations = observations
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'PurchaseOrderData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PurchaseOrderData of this PurchaseOrderData.  # noqa: E501
        :rtype: PurchaseOrderData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_date(self) -> object:
        """Gets the start_date of this PurchaseOrderData.


        :return: The start_date of this PurchaseOrderData.
        :rtype: object
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: object):
        """Sets the start_date of this PurchaseOrderData.


        :param start_date: The start_date of this PurchaseOrderData.
        :type start_date: object
        """

        self._start_date = start_date

    @property
    def end_date(self) -> object:
        """Gets the end_date of this PurchaseOrderData.


        :return: The end_date of this PurchaseOrderData.
        :rtype: object
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: object):
        """Sets the end_date of this PurchaseOrderData.


        :param end_date: The end_date of this PurchaseOrderData.
        :type end_date: object
        """

        self._end_date = end_date

    @property
    def type_order(self) -> str:
        """Gets the type_order of this PurchaseOrderData.


        :return: The type_order of this PurchaseOrderData.
        :rtype: str
        """
        return self._type_order

    @type_order.setter
    def type_order(self, type_order: str):
        """Sets the type_order of this PurchaseOrderData.


        :param type_order: The type_order of this PurchaseOrderData.
        :type type_order: str
        """

        self._type_order = type_order

    @property
    def destiny_id(self) -> int:
        """Gets the destiny_id of this PurchaseOrderData.


        :return: The destiny_id of this PurchaseOrderData.
        :rtype: int
        """
        return self._destiny_id

    @destiny_id.setter
    def destiny_id(self, destiny_id: int):
        """Sets the destiny_id of this PurchaseOrderData.


        :param destiny_id: The destiny_id of this PurchaseOrderData.
        :type destiny_id: int
        """

        self._destiny_id = destiny_id

    @property
    def number_order(self) -> str:
        """Gets the number_order of this PurchaseOrderData.


        :return: The number_order of this PurchaseOrderData.
        :rtype: str
        """
        return self._number_order

    @number_order.setter
    def number_order(self, number_order: str):
        """Sets the number_order of this PurchaseOrderData.


        :param number_order: The number_order of this PurchaseOrderData.
        :type number_order: str
        """

        self._number_order = number_order

    @property
    def quantity(self) -> int:
        """Gets the quantity of this PurchaseOrderData.


        :return: The quantity of this PurchaseOrderData.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this PurchaseOrderData.


        :param quantity: The quantity of this PurchaseOrderData.
        :type quantity: int
        """

        self._quantity = quantity

    @property
    def provider(self) -> str:
        """Gets the provider of this PurchaseOrderData.


        :return: The provider of this PurchaseOrderData.
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider: str):
        """Sets the provider of this PurchaseOrderData.


        :param provider: The provider of this PurchaseOrderData.
        :type provider: str
        """

        self._provider = provider

    @property
    def observations(self) -> str:
        """Gets the observations of this PurchaseOrderData.


        :return: The observations of this PurchaseOrderData.
        :rtype: str
        """
        return self._observations

    @observations.setter
    def observations(self, observations: str):
        """Sets the observations of this PurchaseOrderData.


        :param observations: The observations of this PurchaseOrderData.
        :type observations: str
        """

        self._observations = observations

    @property
    def user(self) -> str:
        """Gets the user of this PurchaseOrderData.


        :return: The user of this PurchaseOrderData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this PurchaseOrderData.


        :param user: The user of this PurchaseOrderData.
        :type user: str
        """

        self._user = user
