# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RegisterLeadData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, names: str=None, phone: str=None, email: str=None, business: str=None, interested: str=None):  # noqa: E501
        """RegisterLeadData - a model defined in Swagger

        :param names: The names of this RegisterLeadData.  # noqa: E501
        :type names: str
        :param phone: The phone of this RegisterLeadData.  # noqa: E501
        :type phone: str
        :param email: The email of this RegisterLeadData.  # noqa: E501
        :type email: str
        :param business: The business of this RegisterLeadData.  # noqa: E501
        :type business: str
        :param interested: The interested of this RegisterLeadData.  # noqa: E501
        :type interested: str
        """
        self.swagger_types = {
            'names': str,
            'phone': str,
            'email': str,
            'business': str,
            'interested': str
        }

        self.attribute_map = {
            'names': 'names',
            'phone': 'phone',
            'email': 'email',
            'business': 'business',
            'interested': 'interested'
        }
        self._names = names
        self._phone = phone
        self._email = email
        self._business = business
        self._interested = interested

    @classmethod
    def from_dict(cls, dikt) -> 'RegisterLeadData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RegisterLeadData of this RegisterLeadData.  # noqa: E501
        :rtype: RegisterLeadData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def names(self) -> str:
        """Gets the names of this RegisterLeadData.


        :return: The names of this RegisterLeadData.
        :rtype: str
        """
        return self._names

    @names.setter
    def names(self, names: str):
        """Sets the names of this RegisterLeadData.


        :param names: The names of this RegisterLeadData.
        :type names: str
        """

        self._names = names

    @property
    def phone(self) -> str:
        """Gets the phone of this RegisterLeadData.


        :return: The phone of this RegisterLeadData.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this RegisterLeadData.


        :param phone: The phone of this RegisterLeadData.
        :type phone: str
        """

        self._phone = phone

    @property
    def email(self) -> str:
        """Gets the email of this RegisterLeadData.


        :return: The email of this RegisterLeadData.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this RegisterLeadData.


        :param email: The email of this RegisterLeadData.
        :type email: str
        """

        self._email = email

    @property
    def business(self) -> str:
        """Gets the business of this RegisterLeadData.


        :return: The business of this RegisterLeadData.
        :rtype: str
        """
        return self._business

    @business.setter
    def business(self, business: str):
        """Sets the business of this RegisterLeadData.


        :param business: The business of this RegisterLeadData.
        :type business: str
        """

        self._business = business

    @property
    def interested(self) -> str:
        """Gets the interested of this RegisterLeadData.


        :return: The interested of this RegisterLeadData.
        :rtype: str
        """
        return self._interested

    @interested.setter
    def interested(self, interested: str):
        """Sets the interested of this RegisterLeadData.


        :param interested: The interested of this RegisterLeadData.
        :type interested: str
        """

        self._interested = interested
