# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.new_user_data import NewUserData  # noqa: F401,E501
from swagger_server import util


class RequestPostNewUser(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, new_user: NewUserData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestPostNewUser - a model defined in Swagger

        :param new_user: The new_user of this RequestPostNewUser.  # noqa: E501
        :type new_user: NewUserData
        :param channel: The channel of this RequestPostNewUser.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestPostNewUser.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'new_user': NewUserData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'new_user': 'new_user',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._new_user = new_user
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestPostNewUser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestPostNewUser of this RequestPostNewUser.  # noqa: E501
        :rtype: RequestPostNewUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def new_user(self) -> NewUserData:
        """Gets the new_user of this RequestPostNewUser.


        :return: The new_user of this RequestPostNewUser.
        :rtype: NewUserData
        """
        return self._new_user

    @new_user.setter
    def new_user(self, new_user: NewUserData):
        """Sets the new_user of this RequestPostNewUser.


        :param new_user: The new_user of this RequestPostNewUser.
        :type new_user: NewUserData
        """

        self._new_user = new_user

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestPostNewUser.


        :return: The channel of this RequestPostNewUser.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestPostNewUser.


        :param channel: The channel of this RequestPostNewUser.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestPostNewUser.


        :return: The external_transaction_id of this RequestPostNewUser.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestPostNewUser.


        :param external_transaction_id: The external_transaction_id of this RequestPostNewUser.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
