# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.login_data import LoginData  # noqa: F401,E501
from swagger_server import util


class RequestLogin(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, login: LoginData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestLogin - a model defined in Swagger

        :param login: The login of this RequestLogin.  # noqa: E501
        :type login: LoginData
        :param channel: The channel of this RequestLogin.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestLogin.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'login': LoginData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'login': 'login',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._login = login
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestLogin':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestLogin of this RequestLogin.  # noqa: E501
        :rtype: RequestLogin
        """
        return util.deserialize_model(dikt, cls)

    @property
    def login(self) -> LoginData:
        """Gets the login of this RequestLogin.


        :return: The login of this RequestLogin.
        :rtype: LoginData
        """
        return self._login

    @login.setter
    def login(self, login: LoginData):
        """Sets the login of this RequestLogin.


        :param login: The login of this RequestLogin.
        :type login: LoginData
        """

        self._login = login

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestLogin.


        :return: The channel of this RequestLogin.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestLogin.


        :param channel: The channel of this RequestLogin.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestLogin.


        :return: The external_transaction_id of this RequestLogin.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestLogin.


        :param external_transaction_id: The external_transaction_id of this RequestLogin.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
