# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.log_book_entry_data import LogBookEntryData  # noqa: F401,E501
from swagger_server import util


class RequestPostLogbookEntry(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, logbook_entry: LogBookEntryData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestPostLogbookEntry - a model defined in Swagger

        :param logbook_entry: The logbook_entry of this RequestPostLogbookEntry.  # noqa: E501
        :type logbook_entry: LogBookEntryData
        :param channel: The channel of this RequestPostLogbookEntry.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestPostLogbookEntry.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'logbook_entry': LogBookEntryData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'logbook_entry': 'logbook_entry',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._logbook_entry = logbook_entry
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestPostLogbookEntry':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestPostLogbookEntry of this RequestPostLogbookEntry.  # noqa: E501
        :rtype: RequestPostLogbookEntry
        """
        return util.deserialize_model(dikt, cls)

    @property
    def logbook_entry(self) -> LogBookEntryData:
        """Gets the logbook_entry of this RequestPostLogbookEntry.


        :return: The logbook_entry of this RequestPostLogbookEntry.
        :rtype: LogBookEntryData
        """
        return self._logbook_entry

    @logbook_entry.setter
    def logbook_entry(self, logbook_entry: LogBookEntryData):
        """Sets the logbook_entry of this RequestPostLogbookEntry.


        :param logbook_entry: The logbook_entry of this RequestPostLogbookEntry.
        :type logbook_entry: LogBookEntryData
        """

        self._logbook_entry = logbook_entry

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestPostLogbookEntry.


        :return: The channel of this RequestPostLogbookEntry.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestPostLogbookEntry.


        :param channel: The channel of this RequestPostLogbookEntry.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestPostLogbookEntry.


        :return: The external_transaction_id of this RequestPostLogbookEntry.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestPostLogbookEntry.


        :param external_transaction_id: The external_transaction_id of this RequestPostLogbookEntry.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
