# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.purchase_order_data import PurchaseOrderData  # noqa: F401,E501
from swagger_server import util


class RequestPostOrder(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, order: PurchaseOrderData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestPostOrder - a model defined in Swagger

        :param order: The order of this RequestPostOrder.  # noqa: E501
        :type order: PurchaseOrderData
        :param channel: The channel of this RequestPostOrder.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestPostOrder.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'order': PurchaseOrderData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'order': 'order',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._order = order
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestPostOrder':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestPostOrder of this RequestPostOrder.  # noqa: E501
        :rtype: RequestPostOrder
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order(self) -> PurchaseOrderData:
        """Gets the order of this RequestPostOrder.


        :return: The order of this RequestPostOrder.
        :rtype: PurchaseOrderData
        """
        return self._order

    @order.setter
    def order(self, order: PurchaseOrderData):
        """Sets the order of this RequestPostOrder.


        :param order: The order of this RequestPostOrder.
        :type order: PurchaseOrderData
        """

        self._order = order

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestPostOrder.


        :return: The channel of this RequestPostOrder.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestPostOrder.


        :param channel: The channel of this RequestPostOrder.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestPostOrder.


        :return: The external_transaction_id of this RequestPostOrder.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestPostOrder.


        :param external_transaction_id: The external_transaction_id of this RequestPostOrder.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestPostOrder':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestPostOrder of this RequestPostOrder.  # noqa: E501
        :rtype: RequestPostOrder
        """
        return util.deserialize_model(dikt, cls)
