# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.employee_movement_data import EmployeeMovementData  # noqa: F401,E501
from swagger_server import util


class RequestPostEmployeeMovement(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, employee_movement: EmployeeMovementData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestPostEmployeeMovement - a model defined in Swagger

        :param employee_movement: The employee_movement of this RequestPostEmployeeMovement.  # noqa: E501
        :type employee_movement: EmployeeMovementData
        :param channel: The channel of this RequestPostEmployeeMovement.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestPostEmployeeMovement.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'employee_movement': EmployeeMovementData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'employee_movement': 'employee_movement',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._employee_movement = employee_movement
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestPostEmployeeMovement':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestPostEmployeeMovement of this RequestPostEmployeeMovement.  # noqa: E501
        :rtype: RequestPostEmployeeMovement
        """
        return util.deserialize_model(dikt, cls)

    @property
    def employee_movement(self) -> EmployeeMovementData:
        """Gets the employee_movement of this RequestPostEmployeeMovement.


        :return: The employee_movement of this RequestPostEmployeeMovement.
        :rtype: EmployeeMovementData
        """
        return self._employee_movement

    @employee_movement.setter
    def employee_movement(self, employee_movement: EmployeeMovementData):
        """Sets the employee_movement of this RequestPostEmployeeMovement.


        :param employee_movement: The employee_movement of this RequestPostEmployeeMovement.
        :type employee_movement: EmployeeMovementData
        """

        self._employee_movement = employee_movement

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestPostEmployeeMovement.


        :return: The channel of this RequestPostEmployeeMovement.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestPostEmployeeMovement.


        :param channel: The channel of this RequestPostEmployeeMovement.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestPostEmployeeMovement.


        :return: The external_transaction_id of this RequestPostEmployeeMovement.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestPostEmployeeMovement.


        :param external_transaction_id: The external_transaction_id of this RequestPostEmployeeMovement.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
