# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.assign_order_data import AssignOrderData  # noqa: F401,E501
from swagger_server import util


class RequestAssignOrder(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: AssignOrderData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestAssignOrder - a model defined in Swagger

        :param data: The data of this RequestAssignOrder.  # noqa: E501
        :type data: AssignOrderData
        :param channel: The channel of this RequestAssignOrder.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestAssignOrder.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'data': AssignOrderData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'data': 'data',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._data = data
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestAssignOrder':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestAssignOrder of this RequestAssignOrder.  # noqa: E501
        :rtype: RequestAssignOrder
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> AssignOrderData:
        """Gets the data of this RequestAssignOrder.


        :return: The data of this RequestAssignOrder.
        :rtype: AssignOrderData
        """
        return self._data

    @data.setter
    def data(self, data: AssignOrderData):
        """Sets the data of this RequestAssignOrder.


        :param data: The data of this RequestAssignOrder.
        :type data: AssignOrderData
        """

        self._data = data

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestAssignOrder.


        :return: The channel of this RequestAssignOrder.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestAssignOrder.


        :param channel: The channel of this RequestAssignOrder.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestAssignOrder.


        :return: The external_transaction_id of this RequestAssignOrder.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestAssignOrder.


        :param external_transaction_id: The external_transaction_id of this RequestAssignOrder.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
