# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.log_book_out_data import LogBookOutData  # noqa: F401,E501
from swagger_server import util


class RequestPostLogbookOut(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, logbook_out: LogBookOutData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestPostLogbookOut - a model defined in Swagger

        :param logbook_out: The logbook_out of this RequestPostLogbookOut.  # noqa: E501
        :type logbook_out: LogBookOutData
        :param channel: The channel of this RequestPostLogbookOut.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestPostLogbookOut.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'logbook_out': LogBookOutData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'logbook_out': 'logbook_out',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._logbook_out = logbook_out
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestPostLogbookOut':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestPostLogbookOut of this RequestPostLogbookOut.  # noqa: E501
        :rtype: RequestPostLogbookOut
        """
        return util.deserialize_model(dikt, cls)

    @property
    def logbook_out(self) -> LogBookOutData:
        """Gets the logbook_out of this RequestPostLogbookOut.


        :return: The logbook_out of this RequestPostLogbookOut.
        :rtype: LogBookOutData
        """
        return self._logbook_out

    @logbook_out.setter
    def logbook_out(self, logbook_out: LogBookOutData):
        """Sets the logbook_out of this RequestPostLogbookOut.


        :param logbook_out: The logbook_out of this RequestPostLogbookOut.
        :type logbook_out: LogBookOutData
        """

        self._logbook_out = logbook_out

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestPostLogbookOut.


        :return: The channel of this RequestPostLogbookOut.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestPostLogbookOut.


        :param channel: The channel of this RequestPostLogbookOut.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestPostLogbookOut.


        :return: The external_transaction_id of this RequestPostLogbookOut.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestPostLogbookOut.


        :param external_transaction_id: The external_transaction_id of this RequestPostLogbookOut.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
