# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.register_lead_data import RegisterLeadData  # noqa: F401,E501
from swagger_server import util


class RequestLead(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, lead: RegisterLeadData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestLead - a model defined in Swagger

        :param lead: The lead of this RequestLead.  # noqa: E501
        :type lead: RegisterLeadData
        :param channel: The channel of this RequestLead.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestLead.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'lead': RegisterLeadData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'lead': 'lead',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._lead = lead
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestLead':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestLead of this RequestLead.  # noqa: E501
        :rtype: RequestLead
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lead(self) -> RegisterLeadData:
        """Gets the lead of this RequestLead.


        :return: The lead of this RequestLead.
        :rtype: RegisterLeadData
        """
        return self._lead

    @lead.setter
    def lead(self, lead: RegisterLeadData):
        """Sets the lead of this RequestLead.


        :param lead: The lead of this RequestLead.
        :type lead: RegisterLeadData
        """

        self._lead = lead

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestLead.


        :return: The channel of this RequestLead.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestLead.


        :param channel: The channel of this RequestLead.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestLead.


        :return: The external_transaction_id of this RequestLead.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestLead.


        :param external_transaction_id: The external_transaction_id of this RequestLead.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
