# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.order_receipts_data import OrderReceiptsData  # noqa: F401,E501
from swagger_server import util


class RequestPostOrderReceipts(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: OrderReceiptsData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestPostOrderReceipts - a model defined in Swagger

        :param data: The data of this RequestPostOrderReceipts.  # noqa: E501
        :type data: OrderReceiptsData
        :param channel: The channel of this RequestPostOrderReceipts.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestPostOrderReceipts.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'data': OrderReceiptsData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'data': 'data',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._order = data
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestPostOrderReceipts':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestPostOrderReceipts of this RequestPostOrderReceipts.  # noqa: E501
        :rtype: RequestPostOrderReceipts
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> OrderReceiptsData:
        """Gets the data of this RequestPostOrderReceipts.


        :return: The data of this RequestPostOrderReceipts.
        :rtype: OrderReceiptsData
        """
        return self._order

    @data.setter
    def data(self, data: OrderReceiptsData):
        """Sets the data of this RequestPostOrderReceipts.


        :param data: The data of this RequestPostOrderReceipts.
        :type data: OrderReceiptsData
        """

        self._order = data

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestPostOrderReceipts.


        :return: The channel of this RequestPostOrderReceipts.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestPostOrderReceipts.


        :param channel: The channel of this RequestPostOrderReceipts.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestPostOrderReceipts.


        :return: The external_transaction_id of this RequestPostOrderReceipts.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestPostOrderReceipts.


        :param external_transaction_id: The external_transaction_id of this RequestPostOrderReceipts.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
