# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.logout_data import LogoutData  # noqa: F401,E501
from swagger_server import util


class RequestLogout(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, logout: LogoutData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestLogout - a model defined in Swagger

        :param logout: The logout of this RequestLogout.  # noqa: E501
        :type logout: LogoutData
        :param channel: The channel of this RequestLogout.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestLogout.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'logout': LogoutData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'logout': 'logout',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._logout = logout
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestLogout':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestLogout of this RequestLogout.  # noqa: E501
        :rtype: RequestLogout
        """
        return util.deserialize_model(dikt, cls)

    @property
    def logout(self) -> LogoutData:
        """Gets the logout of this RequestLogout.


        :return: The logout of this RequestLogout.
        :rtype: LogoutData
        """
        return self._logout

    @logout.setter
    def logout(self, logout: LogoutData):
        """Sets the logout of this RequestLogout.


        :param logout: The logout of this RequestLogout.
        :type logout: LogoutData
        """

        self._logout = logout

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestLogout.


        :return: The channel of this RequestLogout.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestLogout.


        :param channel: The channel of this RequestLogout.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestLogout.


        :return: The external_transaction_id of this RequestLogout.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestLogout.


        :param external_transaction_id: The external_transaction_id of this RequestLogout.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
