# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.employee_intern_data import EmployeeInternData  # noqa: F401,E501
from swagger_server import util


class RequestPostEmployeeIntern(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, employee_intern: EmployeeInternData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestPostEmployeeIntern - a model defined in Swagger

        :param employee_intern: The employee_intern of this RequestPostEmployeeIntern.  # noqa: E501
        :type employee_intern: EmployeeInternData
        :param channel: The channel of this RequestPostEmployeeIntern.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestPostEmployeeIntern.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'employee_intern': EmployeeInternData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'employee_intern': 'employee_intern',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._employee_intern = employee_intern
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestPostEmployeeIntern':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestPostEmployeeIntern of this RequestPostEmployeeIntern.  # noqa: E501
        :rtype: RequestPostEmployeeIntern
        """
        return util.deserialize_model(dikt, cls)

    @property
    def employee_intern(self) -> EmployeeInternData:
        """Gets the employee_intern of this RequestPostEmployeeIntern.


        :return: The employee_intern of this RequestPostEmployeeIntern.
        :rtype: EmployeeInternData
        """
        return self._employee_intern

    @employee_intern.setter
    def employee_intern(self, employee_intern: EmployeeInternData):
        """Sets the employee_intern of this RequestPostEmployeeIntern.


        :param employee_intern: The employee_intern of this RequestPostEmployeeIntern.
        :type employee_intern: EmployeeInternData
        """

        self._employee_intern = employee_intern

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestPostEmployeeIntern.


        :return: The channel of this RequestPostEmployeeIntern.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestPostEmployeeIntern.


        :param channel: The channel of this RequestPostEmployeeIntern.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestPostEmployeeIntern.


        :return: The external_transaction_id of this RequestPostEmployeeIntern.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestPostEmployeeIntern.


        :param external_transaction_id: The external_transaction_id of this RequestPostEmployeeIntern.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
