# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.form_expo_data import FormExpoData  # noqa: F401,E501
from swagger_server import util


class RequestFormExpo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: FormExpoData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestFormExpo - a model defined in Swagger

        :param data: The data of this RequestFormExpo.  # noqa: E501
        :type data: FormExpoData
        :param channel: The channel of this RequestFormExpo.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestFormExpo.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'data': FormExpoData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'data': 'data',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._data = data
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestFormExpo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestFormExpo of this RequestFormExpo.  # noqa: E501
        :rtype: RequestFormExpo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> FormExpoData:
        """Gets the data of this RequestFormExpo.


        :return: The data of this RequestFormExpo.
        :rtype: FormExpoData
        """
        return self._data

    @data.setter
    def data(self, data: FormExpoData):
        """Sets the data of this RequestFormExpo.


        :param data: The data of this RequestFormExpo.
        :type data: FormExpoData
        """

        self._data = data

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestFormExpo.


        :return: The channel of this RequestFormExpo.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestFormExpo.


        :param channel: The channel of this RequestFormExpo.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestFormExpo.


        :return: The external_transaction_id of this RequestFormExpo.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestFormExpo.


        :param external_transaction_id: The external_transaction_id of this RequestFormExpo.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
