# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UpdateStatusEmployeeData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, user_update: str=None):  # noqa: E501
        """UpdateStatusEmployeeData - a model defined in Swagger

        :param status: The status of this UpdateStatusEmployeeData.  # noqa: E501
        :type status: str
        :param user_update: The user_update of this UpdateStatusEmployeeData.  # noqa: E501
        :type user_update: str
        """
        self.swagger_types = {
            'status': str,
            'user_update': str
        }

        self.attribute_map = {
            'status': 'status',
            'user_update': 'user_update'
        }
        self._status = status
        self._user_update = user_update

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateStatusEmployeeData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateStatusEmployeeData of this UpdateStatusEmployeeData.  # noqa: E501
        :rtype: UpdateStatusEmployeeData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this UpdateStatusEmployeeData.


        :return: The status of this UpdateStatusEmployeeData.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this UpdateStatusEmployeeData.


        :param status: The status of this UpdateStatusEmployeeData.
        :type status: str
        """

        self._status = status

    @property
    def user_update(self) -> str:
        """Gets the user_update of this UpdateStatusEmployeeData.


        :return: The user_update of this UpdateStatusEmployeeData.
        :rtype: str
        """
        return self._user_update

    @user_update.setter
    def user_update(self, user_update: str):
        """Sets the user_update of this UpdateStatusEmployeeData.


        :param user_update: The user_update of this UpdateStatusEmployeeData.
        :type user_update: str
        """

        self._user_update = user_update
